name: Create Release

on:
  push:
    tags:
      - "v*"

permissions:
  contents: write

jobs:
  build-and-release:
    runs-on: windows-latest

    defaults:
      run:
        working-directory: ./src

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '8.0.x'

      - name: Restore dependencies
        run: dotnet restore

      - name: Build
        run: dotnet build --configuration Release --no-restore

      - name: Publish
        run: dotnet publish b64.csproj -c Release --property:PublishDir=../publish

      - name: Create Release Zip
        run: |
          $version = "${{ github.ref_name }}" -replace '^v', ''
          Compress-Archive -Path "../publish/*" -DestinationPath "../b64-$version.zip" -Force

      - name: Create GitHub Release
        run: |
          $tag = "${{ github.ref_name }}"
          $version = $tag -replace '^v', ''
          gh release create $tag `
            --repo="$env:GITHUB_REPOSITORY" `
            --title="$version" `
            --generate-notes `
            --latest `
            "../b64-$version.zip"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          GITHUB_REPOSITORY: ${{ github.repository }}
